install dccp /bin/true
install sctp /bin/true
install rds /bin/true
install tipc /bin/true
# esp has been used by dirtyfrag and dirtyclone (and probably more)
install esp4 /bin/true
install esp6 /bin/true
install rxrpc /bin/true
