# xt_TEE has been exploited in CVE-2026-43503 (dirtyclone)
# we don't need it in Tails
install xt_TEE /bin/true

# act_pedit provides the functionality which is required by tc(8)
# we don't use it in Tails, and it's been used in CVE-2026-46331 (aka PACKET_EDIT_MEME)
install act_pedit /bin/true
